log_name: 'tmss_HN12022_0'

# path
results: '../results'
data: '../../datasets_TCIA'
#dataset: 'HECKTOR2022'
#tabular: 'clinical_norm.csv'
#intervals: [0, 300, 600, 900, 1100, 1300, 1500, 2100, 2700, 3500, 6000]
#time_spots: [1, 4, 7]
dataset: 'HN1'
tabular: 'clinical_norm_complete.csv'
intervals: [0, 336, 673, 1009, 1346, 1683, 2019, 2356, 2692, 3029, 3366]
time_spots: [1, 3, 5]
interval_num: 10
trained_model: ['', '', '', '', '']
best_ci: [0., 0., 0., 0., 0.]

# model
#t_dim: 15
t_dim: 18

# train
mode: 'train'   # of {'train', 'test'}
device: '0'     # of {'0', '1'}
seed: 24
fold_num: 5

epoch_num: 60
epoch_start_save: 10
batch_size: 2
batch_size_eval: 1

num_workers: 4
pin_memory: True

color:
  train: '#f14461'
  eval: '#3498db'
  test: '#27ce82'
